import 'package:flutter/widgets.dart';
import '../l10n/l10n.dart';

String softposText(BuildContext context, String key) {
  final l = L10n.of(context);
  return switch (key) {
    'title' => l.pay002Title,
    'void' => l.pay002Void,
    'refund' => l.pay002Refund,
    'payment' => l.pay002Payment,
    'reason' => l.pay002Reason,
    'custom' => l.pay002Custom,
    'lines' => l.pay002Lines,
    'remaining' => l.pay002Remaining,
    'managerPin' => l.pay002ManagerPin,
    'continue' => l.pay002Continue,
    'cancel' => l.pay002Cancel,
    'confirm' => l.pay002Confirm,
    'progress' => l.pay002Progress,
    'recovery' => l.pay002Recovery,
    'report' => l.pay002Report,
    'retryReport' => l.pay002RetryReport,
    'reprint' => l.pay002Reprint,
    'printFailed' => l.pay002PrintFailed,
    'receiptJson' => l.pay002ReceiptJson,
    'operator' => l.pay002Operator,
    'noPayments' => l.pay002NoPayments,
    'online' => l.pay002Online,
    'checkTerminal' => l.pay002CheckTerminal,
    'terminal' => l.pay002Terminal,
    'payingVia' => l.pay002PayingVia,
    'firstLaunch' => l.pay002FirstLaunch,
    'no_terminal_credentials' => l.pay002Noterminalcredentials,
    'softpos_unavailable' => l.pay002Softposunavailable,
    'softpos_not_configured' => l.pay002Softposnotconfigured,
    'softpos_mismatch' => l.pay002Softposmismatch,
    'softpos_app_update_required' => l.pay002Softposappupdaterequired,
    'card_blocked' => l.pay002Cardblocked,
    'select' => l.pay002Select,
    'done' => l.pay002Done,
    'approved' => l.pay002Approved,
    'declined' => l.pay002Declined,
    'uncertain' => l.pay002Uncertain,
    'cancelled' => l.pay002Cancelled,
    'responseCode' => l.pay002ResponseCode,
    'rrn' => l.pay002Rrn,
    'authCode' => l.pay002AuthCode,
    'managerCheck' => l.pay002ManagerCheck,
    _ => key,
  };
}
